from .main.home import HomePage as Home
from .tools.posterboard import PosterboardPage as Posterboard
from .tools.gestalt import GestaltPage as MobileGestalt
from .tools.eligibility import EligibilityPage as Eligibility
from .tools.featureflags import FeatureFlagsPage as FeatureFlags
from .tools.status_bar import StatusBarPage as StatusBar
from .tools.springboard import SpringboardPage as Springboard
from .tools.internal import InternalPage as Internal
from .tools.liquidglass import LiquidGlassPage as LiquidGlass
from .tools.daemons import DaemonsPage as Daemons
from .tools.templates import TemplatesPage as Templates
from .tools.passcode import PasscodePage as Passcode
from .tools.risky import RiskyPage as Risky
from .main.settings import SettingsPage as Settings